name: Release
on:
  push:
    tags: ["v[0-9 ]+.[0 -9 ]+.[0 -9 ]+"]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Registry Login (ghcr.io)
        run: |
          echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and Push Docker Image
        run: |
          IMG=ghcr.io/${{ github.repository }}
          docker build --tag $IMG:latest .
          docker push --all-tags $IMG
