name: Release
permissions: write-all
on:
  push:
    tags: ["v[0-9]+\.[0-9]+\.[0-9]+(-.*)?"]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Registry Login (ghcr.io)
        run: |
          echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_API_KEY: ${{ secrets.API_KEY }}
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          envkey_DEBUG: True
          envkey_ALLOWED_HOSTS: ".localhost, 127.0.0.1, 0.0.0.0"
          file_name: .env
          fail_on_empty: true
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:latest
